"""Builds admin-pages.js: for every paper in pyqs/, the PDF page where each question Q.1..Q.65 starts.
Run from repo root:  pip install pypdf  &&  python tools/build_pdf_pages.py"""
import json, re, pypdf

FILES = {'22': 'CS_2022', '23': 'CS_2023', '24-S1': 'CS1_2024', '24-S2': 'CS2_2024',
         '25-S1': 'CS1_2025', '25-S2': 'CS2_2025', '26-S1': 'CS1_2026', '26-S2': 'CS2_2026'}
out = {}
for tag, f in FILES.items():
    first = {}
    for i, pg in enumerate(pypdf.PdfReader(f'pyqs/{f}.pdf').pages, 1):
        for m in re.finditer(r'(?m)^\s*Q\.\s*(\d+)\b', pg.extract_text() or ''):
            n = int(m.group(1))
            if 1 <= n <= 65: first.setdefault(n, i)
    seq = [first[n] for n in sorted(first)]
    assert all(a <= b for a, b in zip(seq, seq[1:])), f'{f}: page order not monotonic'
    arr, last = [], None
    for n in range(1, 66):          # a question whose marker was not found takes the previous question's page
        last = first.get(n, last)
        arr.append(last)
    miss = [n for n in range(1, 66) if n not in first]
    print(f, 'ok' if not miss else f'fallback used for Q{miss}')
    out[tag] = arr
open('admin-pages.js', 'w', encoding='utf-8').write(
    '// AUTO-GENERATED by tools/build_pdf_pages.py — PAGES[tag][n-1] = PDF page where question n starts.\n'
    'export const PAGES = ' + json.dumps(out, separators=(',', ':')) + ';\n')
